### ISSUE TITLE
Multi-column layout for messages in message pane

### ISSUE THREAD

**Issue by Kalmalyzer** [bbbscarter/UberLogger#15]
Currently there are two columns in the message pane: The message type indicator column, and then the text column.

The text column contains either just the message, or it contains timestamp + message.

Formatting becomes weird when timestamps are visible, and a multiline message is printed (see screenshot).

I think it would be preferable to divide the message pane into columns like this:

- message type
- timestamp (can be disabled/enabled via buttons on the UberLogger toolbar)
- channel (can be disabled/enabled via buttons on the UberLogger toolbar)
- message text

This would either require a heading row for the message pane, so that the user can adjust the relative width of each column -- or the message pane would need to analyze strings as they get added, find the maximum width for each column widths, and automatically adjust the display of all message entries accordingly.

**Comment by bbbscarter** [comment]
With the newly fixed single-line behaviour, am I good to close this?

**Comment by Kalmalyzer** [comment]
Good point - with no multi-line messages this will not make much of a difference.
