### ISSUE TITLE
UberDebug.Log() uses Warning severity instead of Message

### ISSUE THREAD

**Issue by xrix4096** [bbbscarter/UberLogger#16]
This is easy to fix but I'm questioning whether it has been done deliberately. The UberDebug.LogChannel() methods use the Message severity level as I expect but non-channel ones use Warning. This seems odd since I have LogWarning() methods to use if I want that severity.

Code change appears to be just changing from Warning to Message in the first two methods in UberDebug.cs, can pull request if required

**Comment by bbbscarter** [comment]
Yup - I think you're right, and this is just a typo. Not sure how that slipped through - good spot! Feel free to PR.

**Comment by xrix4096** [comment]
Will do :-)
