### ISSUE TITLE
Double Click on Log Entry does not the same as in Unity Debug window.

### ISSUE THREAD

**Issue by michidk** [bbbscarter/UberLogger#18]
Double Click on a Log Entry in the Unity Debug Window opens Visual Studio.
Double Click on a Log Entry in the Uber Console opens Sublime Text for me.

Can this somehow changed, so that Uber Console opens the editor which is set in the Unity Editor preferences?

**Comment by Kalmalyzer** [comment]
This might be related to https://github.com/bbbscarter/UberLogger/pull/2 . With the current implementation, I notice that some paths open in MonoDevelop while other paths open in Visual Studio.

**Comment by Kalmalyzer** [comment]
@Michidk can you repro this? I know it sometimes happens but cannot repro it myself now. If you can, would you also be able to breakpoint on the line where UnityEditorInternal.InternalEditorUtility.OpenFileAtLineExternal is called, and tell us what arguments are being passed to that function?

**Comment by michidk** [comment]
So this happens on both machines where i tested... Both of them running Unity 5.5 and having Sublime Text installed.
I noticed that Sublime Text only opens when Visual Studio is open. If Visual Studio is not running, a doubleclick always opens VS on the correct line.

Sadly after I added a Debug.Log line to print out the parameters of `OpenFileAtLineExternal `, it worked again.

**Comment by Kalmalyzer** [comment]
Yeah, using debug.log for capturing results is "dangerous" whenever we deal with a tool that is intended to hook console logging; that is why I suggest putting a breakpoint on the line and inspecting variables in scope instead (and copy/pasting the exact results to this ticket so we have something more meaty to go on).

It should be possible to do it like this:
1) dev normally
2) once you notice that a file opened in the wrong editor, place a breakpoint, attach to Unity, and attempt again to open the same exact file
3) inspect method arguments

**Comment by michidk** [comment]
Didn't know you can debug editor stuff. Awesome!

Here is the result:
![VS](https://cloud.githubusercontent.com/assets/3979930/23867470/4773f42a-081c-11e7-8182-a6c3e699b60d.png)

**Comment by Kalmalyzer** [comment]
Thanks -- I got a repro of it just now. It is a Windows specific problem, having to do with forward vs backward slashes.

This opens correctly in my editor of choice:
```
-		frame	{UberLogger.LogStackFrame}	UberLogger.LogStackFrame
		DeclaringType	"PendingUnitAbility"	System.String
		FileName	"C:\\Plastic\\FreedomPrototype\\Assets\\Scripts\\PendingUnitAbility.cs"	System.String
		FormattedMethodName	"PendingUnitAbility.Execute(System.Action completionCallback) (at Assets\\Scripts\\PendingUnitAbility.cs:86)"	System.String
		LineNumber	86	System.Int32
		MethodName	"Execute"	System.String
		ParameterSig	"System.Action completionCallback"	System.String
````

This opens in the wrong editor:
```
-		frame	{UberLogger.LogStackFrame}	UberLogger.LogStackFrame
		DeclaringType	"FireAgainstUnitVisualTrigger+<AimThenFire>c__Iterator0"	System.String
		FileName	"Assets/Scripts/Abilities/VisualTriggers/FireAgainstUnitVisualTrigger.cs"	System.String
		FormattedMethodName	"FireAgainstUnitVisualTrigger+<AimThenFire>c__Iterator0.MoveNext () (at Assets/Scripts/Abilities/VisualTriggers/FireAgainstUnitVisualTrigger.cs:41)"	System.String
		LineNumber	41	System.Int32
		MethodName	"MoveNext "	System.String
		ParameterSig	null	System.String
```

Your screenshot is also one with forward slashes. When I look around at callstacks in my application it seems that paths come in three forms with the current UberLogger stacktrace code:

- `C:\buildslave\unity\...` - Unity's internal callstacks. We do not have source so these are not openable.
- `Assets\blah\...` - Code from my project
- `Assets/blah/...`- Code from my project
The third form does not open correctly.

There are several things we could do to sort this out:
* Ensure that paths are always presented with backslashes on Windows. Before doing that, I wonder why there is a mix of forward- and backward-slashes though. Does that have to do with there being two methods for retrieving callstacks? Is this perhaps Unity 4.x legacy? Is it a good idea to have both?
* Follow up on https://github.com/bbbscarter/UberLogger/pull/2 and change the open-file call method to something else. Changing that has a downside in that paths outside of Assets/ will not open correctly. I'm not sure when those would appear... perhaps when using pre-built binaries / when splitting a Unity project over multiple build steps, if that is at all possible?

**Comment by Kalmalyzer** [comment]
@bbbscarter What's the reason for having two different methods for retrieving callstacks? Is this to do with 4.x + 5.x compatibility? Do you know of specific situations where one method works better than the other?

**Comment by bbbscarter** [comment]
One of them is for intercepting callstacks that come directly from Unity (e.g. Debug.Logxxx), the other is for intercepting callstacks from UberLogger itself (e.g. UberDebug.Logxxx). The former is slow and tries to fill in bits of missing info by parsing the already-stringified callstacks; the latter is fast and robust.

(Assuming those are the two paths you mean).

**Comment by Kalmalyzer** [comment]
Hmm. It appears that the homemade stack-walk is being used for Debug.Logxxx calls as well. It is only if that walk totally fails that UberLogger falls back on parsing the Unity-provided multi-line string.

Unity does not show paths to internal code (i.e. `C:\buildslave\Unity\...`) and if there are multiple of these in the callstack it will collapse them (so I think you just see the "entry point").

Anyway, to the matter at hand; I think the right thing to do is to change folder separators in any paths to `Assets\blah\...` format on Windows before calling `UnityEditorInternal.InternalEditorUtility.OpenFileAtLineExternal`.
