### ISSUE TITLE
didn't work in untiiy 5.6.1f 64bit.

### ISSUE THREAD

**Issue by midgithub** [bbbscarter/UberLogger#28]
fix .it's my problem~.

**Comment by midGitub** [comment]
![qq 20170606222600](https://cloud.githubusercontent.com/assets/20261416/26834170/2e11d5dc-4b07-11e7-9e8b-e7e253ef282d.png)
it seems strange that i run the example even i check that the code had derived from monobehavior

**Comment by Kalmalyzer** [comment]
@midGitub Okay -- if all is well, please also close this issue.
