### ISSUE TITLE
Debug static class conflicts with other uses

### ISSUE THREAD

**Issue by sinbad** [bbbscarter/UberLogger#3]
Thanks for UberLogger!

I had one issue which is that making it a drop-in replacement with the global static class `Debug` conflicts with several use cases for me, including dropping in the standard Unity Test Tools. 

There are 2 issues I've seen and the test tools trigger both of them: 
1. Anything which tries to access the property `Debug.isDebugBuild` fails and I don't believe it's possible to fix that by proxying since C# doesn't allow properties on static classes, or global variables which you'd need to proxy it with an instance.
2. `using Debug = UnityEngine.Debug;` because you're also importing `System.Diagnostics` conflicts with the global namespace `Debug`

I've fixed this in my projects by just renaming the `Debug` class `UberDebug` because I don't really mind that it's not a drop-in replacement and that I need to use it specifically (it's still a nice shortcut over `UberLogger.Logger.Log`). I don't know if you want a PR for this though since one of the highlighted features is that it's a drop-in replacement - although sometimes it isn't if your code has either of the 2 issues above 😉 Maybe you can think of a better way to mitigate this, or maybe this could just be in the docs as a gotcha.

Thanks again!

**Comment by bbbscarter** [comment]
Hi Steve! 

I'm trying to remember why I implemented it via a Debug aliasing class - I seem to remember it was:
a) I was having difficulty intercepting all Unity messages, and thus capturing existing calls via function spoofing was necessary.
b) I initially had versions of 'Log'/etc with just extra parameters for channels and stuff. 

I'm 90% sure a) is no longer true, and b) is definitely not true, so I think the solution of renaming the class is actually fine. I'll give it a quick go now (I'm adding some new features anyway).

Ta!

Simon

**Comment by bbbscarter** [comment]
FYI, I’ve just created a ‘version 2’ branch, which has the following:
- Completely rewritten the renderer - the ‘easy’ way was slow and made supporting other features a nightmare. 
- Added support for ‘collapse’.
- Added support for ‘autoscroll/follow’.
- Removed the old ‘Debug’ namespace spoofing - it was causing problems for people. All the UberLogger debug commands are now in UberDebug - Debug.Log will still be intercepted correctly, however.
- Better selection of colouring - should now work with Pro skins.

Let me know if this fixes your original issue, or if it creates new problems - then changes are fairly extensive, so I'll only pull it back into main when I'm sure it's safe.

Simon

**Comment by sinbad** [comment]
Wow, thanks Simon, that's way more than I was expecting! 😄 I'm going to check this out properly tomorrow...

**Comment by sinbad** [comment]
Works great for me, thanks so much for the fast response! I just submitted a small warnings cleanup as a PR but otherwise just works & doesn't have the conflicts any more. :metal:  🎉
